baseURL = "https://fcastellanos.io/"
languageCode = "en-us"
title = "Fernando's Blog"
theme = "jeffprod"

[params]
    twitterUser = "fcastellanos"
    githubUser = "fcastellanos"
    youtubeUser = "fcastellanos"

[permalinks]
    post = "/:year/:month/:day/:filename"
[taxonomies]
    tag = "tags"
    archive = "archives"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
  